# Generated by Django 2.2 on 2019-05-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyprovider',
            name='api_id',
            field=models.TextField(blank=True),
        ),
    ]
